// Base de datos oficial de 220 palabras para Primer Grado (School Competitions 2026)
// Organizadas dinámicamente en 5 niveles progresivos para niños de 7 años.

const WORDS_DATA = [
  // ==========================================
  // NIVEL 1: Primeros Pasos (Palabras de 3-4 letras)
  // ==========================================
  {
    id: "w1",
    word: "pen",
    level: 1,
    phonetic: "pen",
    spanish: "Pluma / Bolígrafo",
    synonyms: ["marker", "ballpoint", "lápiz de tinta"],
    howToUseEs: "Usa 'pen' cuando vayas a escribir o dibujar con tinta. Para hacer una oración, combina con 'I have a...' (Yo tengo un...) o 'This is a...' (Este es un...).",
    exampleEn: "I write with a blue pen.",
    exampleEs: "Escribo con una pluma azul."
  },
  {
    id: "w2",
    word: "pet",
    level: 1,
    phonetic: "pet",
    spanish: "Mascota / Acariciar",
    synonyms: ["animal friend", "companion", "mascotita"],
    howToUseEs: "Usa 'pet' para hablar de tu perrito, gatito o animal de casa. También significa acariciar con amor a un animalito.",
    exampleEn: "My dog is a cute pet.",
    exampleEs: "Mi perro es una mascota tierna."
  },
  {
    id: "w3",
    word: "pig",
    level: 1,
    phonetic: "pig",
    spanish: "Cerdo / Cerdito",
    synonyms: ["piglet", "hogly", "puerquito"],
    howToUseEs: "Usa 'pig' para referirte a este amigable animal de granja que dice 'oink oink'.",
    exampleEn: "The pink pig likes mud.",
    exampleEs: "Al cerdo rosado le gusta el lodo."
  },
  {
    id: "w4",
    word: "pin",
    level: 1,
    phonetic: "pin",
    spanish: "Alfiler / Broche",
    synonyms: ["clip", "fastener", "alfilerito"],
    howToUseEs: "Usa 'pin' cuando hables de un pequeño objeto para sujetar ropa o papeles con cuidado.",
    exampleEn: "She put a pin on her jacket.",
    exampleEs: "Ella puso un broche en su chaqueta."
  },
  {
    id: "w5",
    word: "pot",
    level: 1,
    phonetic: "pot",
    spanish: "Olla / Maceta",
    synonyms: ["pan", "vessel", "cacerola"],
    howToUseEs: "Usa 'pot' para hablar de la olla donde mamá o papá cocinan la sopa, o la maceta de una planta.",
    exampleEn: "The soup is in the pot.",
    exampleEs: "La sopa está en la olla."
  },
  {
    id: "w6",
    word: "pup",
    level: 1,
    phonetic: "pap",
    spanish: "Perrito / Cachorro",
    synonyms: ["puppy", "doggy", "cachorrito"],
    howToUseEs: "Usa 'pup' cuando veas a un perro bebé juguetón y chiquito.",
    exampleEn: "The little pup runs fast.",
    exampleEs: "El pequeño cachorro corre rápido."
  },
  {
    id: "w7",
    word: "rat",
    level: 1,
    phonetic: "rat",
    spanish: "Ratón / Rata",
    synonyms: ["rodent", "mouse", "roedor"],
    howToUseEs: "Usa 'rat' para nombrar a un pequeño animalito de cola larga muy curioso.",
    exampleEn: "The rat ate the cheese.",
    exampleEs: "El ratón se comió el queso."
  },
  {
    id: "w8",
    word: "red",
    level: 1,
    phonetic: "red",
    spanish: "Rojo",
    synonyms: ["crimson", "scarlet", "colorado"],
    howToUseEs: "Usa 'red' para describir cosas del color de la manzana o las fresas.",
    exampleEn: "I have a bright red ball.",
    exampleEs: "Tengo una pelota roja brillante."
  },
  {
    id: "w9",
    word: "run",
    level: 1,
    phonetic: "ran",
    spanish: "Correr",
    synonyms: ["dash", "sprint", "trotar"],
    howToUseEs: "Usa 'run' para acciones rápidas en el parque o en deportes. ¡I like to run!",
    exampleEn: "We run in the park.",
    exampleEs: "Nosotros corremos en el parque."
  },
  {
    id: "w10",
    word: "sad",
    level: 1,
    phonetic: "sad",
    spanish: "Triste",
    synonyms: ["unhappy", "down", "apenado"],
    howToUseEs: "Usa 'sad' para describir un sentimiento cuando algo no sale como querías.",
    exampleEn: "Do not be sad, smile!",
    exampleEs: "¡No estés triste, sonríe!"
  },
  {
    id: "w11",
    word: "six",
    level: 1,
    phonetic: "six",
    spanish: "Seis (6)",
    synonyms: ["number 6", "half a dozen"],
    howToUseEs: "Usa 'six' cuando cuentes hasta el número 6.",
    exampleEn: "I see six little birds.",
    exampleEs: "Veo seis pajaritos."
  },
  {
    id: "w12",
    word: "sun",
    level: 1,
    phonetic: "san",
    spanish: "Sol",
    synonyms: ["sunlight", "daystar", "solecito"],
    howToUseEs: "Usa 'sun' para hablar de la estrella brillante y caliente que ilumina el día.",
    exampleEn: "The sun shines in the sky.",
    exampleEs: "El sol brilla en el cielo."
  },
  {
    id: "w13",
    word: "top",
    level: 1,
    phonetic: "top",
    spanish: "Arriba / Cima / Trompo",
    synonyms: ["peak", "highest part", "trompito"],
    howToUseEs: "Usa 'top' para indicar la parte más alta de algo (ej: top of the mountain).",
    exampleEn: "The cat is on top of the box.",
    exampleEs: "El gato está arriba de la caja."
  },
  {
    id: "w14",
    word: "cup",
    level: 1,
    phonetic: "cap",
    spanish: "Taza / Vaso",
    synonyms: ["mug", "glass", "tazita"],
    howToUseEs: "Usa 'cup' para el recipiente donde tomas tu leche o chocolate caliente.",
    exampleEn: "My cup is full of warm milk.",
    exampleEs: "Mi taza está llena de leche tibia."
  },
  {
    id: "w15",
    word: "cut",
    level: 1,
    phonetic: "cat",
    spanish: "Cortar",
    synonyms: ["slice", "snip", "recortar"],
    howToUseEs: "Usa 'cut' cuando uses tijeras de papel para manualidades con cuidado.",
    exampleEn: "I cut the paper with scissors.",
    exampleEs: "Corto el papel con las tijeras."
  },
  {
    id: "w16",
    word: "dog",
    level: 1,
    phonetic: "dog",
    spanish: "Perro",
    synonyms: ["puppy", "canine", "perrito"],
    howToUseEs: "Usa 'dog' para nombrar al amigo de cuatro patas que ladra 'woof woof'.",
    exampleEn: "My dog loves to play catch.",
    exampleEs: "A mi perro le encanta jugar a atrapar."
  },
  {
    id: "w17",
    word: "egg",
    level: 1,
    phonetic: "eg",
    spanish: "Huevo",
    synonyms: ["oval food", "huevito"],
    howToUseEs: "Usa 'egg' para hablar del alimento nutritivo que ponen las gallinas.",
    exampleEn: "I eat an egg for breakfast.",
    exampleEs: "Como un huevo para el desayuno."
  },
  {
    id: "w18",
    word: "fan",
    level: 1,
    phonetic: "fan",
    spanish: "Ventilador / Abanico",
    synonyms: ["blower", "cooler", "ventiladorcito"],
    howToUseEs: "Usa 'fan' cuando haga calor y enciendas el aparato que soplare aire fresco.",
    exampleEn: "Turn on the fan, it is hot.",
    exampleEs: "Enciende el ventilador, hace calor."
  },
  {
    id: "w19",
    word: "fat",
    level: 1,
    phonetic: "fat",
    spanish: "Gordito / Abundante",
    synonyms: ["plump", "chubby", "gordinflón"],
    howToUseEs: "Usa 'fat' para describir algo gordito o pachón como un oso de peluche.",
    exampleEn: "The fat cat sleeps all day.",
    exampleEs: "El gato gordito duerme todo el día."
  },
  {
    id: "w20",
    word: "fin",
    level: 1,
    phonetic: "fin",
    spanish: "Aleta (de pez)",
    synonyms: ["flipper", "aleta"],
    howToUseEs: "Usa 'fin' para señalar la parte del cuerpo del pez o tiburón que le ayuda a nadar.",
    exampleEn: "The fish wiggles its fin.",
    exampleEs: "El pez mueve su aleta."
  },
  {
    id: "w21",
    word: "hat",
    level: 1,
    phonetic: "jat",
    spanish: "Sombrero / Gorro",
    synonyms: ["cap", "bonnet", "gorrita"],
    howToUseEs: "Usa 'hat' cuando te pones algo en la cabeza para protegerte del sol.",
    exampleEn: "He wears a big yellow hat.",
    exampleEs: "Él usa un sombrero amarillo grande."
  },
  {
    id: "w22",
    word: "hen",
    level: 1,
    phonetic: "jen",
    spanish: "Gallina",
    synonyms: ["chicken", "fowl", "gallinita"],
    howToUseEs: "Usa 'hen' para hablar de la mamá gallina que pone huevos en la granja.",
    exampleEn: "The hen clucks in the yard.",
    exampleEs: "La gallina cacarea en el patio."
  },
  {
    id: "w23",
    word: "hop",
    level: 1,
    phonetic: "jop",
    spanish: "Saltar en un pie / Dar un brinquito",
    synonyms: ["jump", "bounce", "brincar"],
    howToUseEs: "Usa 'hop' para dar saltitos cortos como los conejos o los pajaritos.",
    exampleEn: "Rabbits like to hop fast.",
    exampleEs: "A los conejos les gusta dar saltitos rápido."
  },
  {
    id: "w24",
    word: "hot",
    level: 1,
    phonetic: "jot",
    spanish: "Caliente / Caluroso",
    synonyms: ["warm", "spicy", "calientito"],
    howToUseEs: "Usa 'hot' cuando el sol quema mucho o cuando la sopa acaba de salir de la cocina.",
    exampleEn: "The cocoa soup is hot.",
    exampleEs: "La sopa de chocolate está caliente."
  },
  {
    id: "w25",
    word: "hug",
    level: 1,
    phonetic: "jag",
    spanish: "Abrazo / Abrazar",
    synonyms: ["cuddle", "squeeze", "abrazote"],
    howToUseEs: "Usa 'hug' cuando le des un abrazo lleno de cariño a tu mamá, papá o amigo.",
    exampleEn: "I give my mom a big hug.",
    exampleEs: "Le doy un gran abrazo a mi mamá."
  },
  {
    id: "w26",
    word: "jar",
    level: 1,
    phonetic: "dyar",
    spanish: "Frasco / Tarro",
    synonyms: ["pot", "container", "frasquito"],
    howToUseEs: "Usa 'jar' para guardar galletas, mermelada o caramelos en la cocina.",
    exampleEn: "The cookies are in the glass jar.",
    exampleEs: "Las galletas están en el frasco de vidrio."
  },
  {
    id: "w27",
    word: "jet",
    level: 1,
    phonetic: "djet",
    spanish: "Avión a reacción / Jet",
    synonyms: ["plane", "airplane", "avión rápido"],
    howToUseEs: "Usa 'jet' para referirte a los aviones súper rápidos que vuelan alto en las nubes.",
    exampleEn: "The jet flies high in the sky.",
    exampleEs: "El jet vuela alto en el cielo."
  },
  {
    id: "w28",
    word: "leg",
    level: 1,
    phonetic: "leg",
    spanish: "Pierna",
    synonyms: ["limb", "foot base", "piernita"],
    howToUseEs: "Usa 'leg' para nombrar la parte de tu cuerpo que usas para caminar y patear el balón.",
    exampleEn: "I can stand on one leg.",
    exampleEs: "Puedo pararme en una sola pierna."
  },
  {
    id: "w29",
    word: "man",
    level: 1,
    phonetic: "man",
    spanish: "Hombre / Señor",
    synonyms: ["gentleman", "adult male", "señor"],
    howToUseEs: "Usa 'man' para referirte a un adulto masculino como papá o el maestro.",
    exampleEn: "The kind man helped us.",
    exampleEs: "El hombre amable nos ayudó."
  },
  {
    id: "w30",
    word: "mop",
    level: 1,
    phonetic: "mop",
    spanish: "Trapeador / Trapear",
    synonyms: ["broom", "cleaner", "trapeadorcito"],
    howToUseEs: "Usa 'mop' cuando limpies el suelo de la casa con agua.",
    exampleEn: "Use the mop to clean the kitchen.",
    exampleEs: "Usa el trapeador para limpiar la cocina."
  },
  {
    id: "w31",
    word: "mug",
    level: 1,
    phonetic: "mag",
    spanish: "Taza grande",
    synonyms: ["cup", "jarra", "tazota"],
    howToUseEs: "Usa 'mug' para una taza grande con asa ideal para chocolate caliente.",
    exampleEn: "Dad drinks coffee from his big mug.",
    exampleEs: "Papá toma café en su taza grande."
  },
  {
    id: "w32",
    word: "one",
    level: 1,
    phonetic: "wan",
    spanish: "Uno (1)",
    synonyms: ["single", "number 1"],
    howToUseEs: "Usa 'one' para contar la primera cantidad de algo.",
    exampleEn: "I have one nose and two eyes.",
    exampleEs: "Tengo una nariz y dos ojos."
  },
  {
    id: "w33",
    word: "pan",
    level: 1,
    phonetic: "pan",
    spanish: "Sartén",
    synonyms: ["skillet", "frying pan", "sartencito"],
    howToUseEs: "Usa 'pan' para hablar de donde freímos los huevos o panqueques.",
    exampleEn: "Cook the egg in the pan.",
    exampleEs: "Cocina el huevo en el sartén."
  },
  {
    id: "w34",
    word: "paw",
    level: 1,
    phonetic: "po",
    spanish: "Pata (de animal)",
    synonyms: ["foot", "pad", "patita"],
    howToUseEs: "Usa 'paw' para referirte al piecito suave de un perro, gato u oso.",
    exampleEn: "The puppy has a fluffy paw.",
    exampleEs: "El perrito tiene una pata esponjosa."
  },
  {
    id: "w35",
    word: "wet",
    level: 1,
    phonetic: "wet",
    spanish: "Mojado / Húmedo",
    synonyms: ["damp", "soaked", "mojadito"],
    howToUseEs: "Usa 'wet' cuando te laves las manos o camines bajo la lluvia.",
    exampleEn: "My shoes got wet in the rain.",
    exampleEs: "Mis zapatos se mojaron en la lluvia."
  },
  {
    id: "w36",
    word: "wig",
    level: 1,
    phonetic: "wig",
    spanish: "Peluca",
    synonyms: ["hairpiece", "fake hair"],
    howToUseEs: "Usa 'wig' para hablar de cabello postizo para disfraces divertidos.",
    exampleEn: "The clown wears a funny red wig.",
    exampleEs: "El payaso usa una peluca roja divertida."
  },
  {
    id: "w37",
    word: "win",
    level: 1,
    phonetic: "win",
    spanish: "Ganar",
    synonyms: ["triumph", "prevail", "triunfar"],
    howToUseEs: "Usa 'win' cuando seas el primero en un juego o competencia de Spelling Bee.",
    exampleEn: "We want to win the game!",
    exampleEs: "¡Queremos ganar el juego!"
  },
  {
    id: "w38",
    word: "zoo",
    level: 1,
    phonetic: "su",
    spanish: "Zoológico",
    synonyms: ["animal park", "safari"],
    howToUseEs: "Usa 'zoo' cuando visites el parque donde viven leones, jirafas y monos.",
    exampleEn: "We saw monkeys at the zoo.",
    exampleEs: "Vimos monos en el zoológico."
  },
  {
    id: "w39",
    word: "box",
    level: 1,
    phonetic: "boks",
    spanish: "Caja",
    synonyms: ["carton", "chest", "cajita"],
    howToUseEs: "Usa 'box' para guardar tus juguetes o cuando recibas un regalo.",
    exampleEn: "Put the toys inside the wooden box.",
    exampleEs: "Pon los juguetes dentro de la caja de madera."
  },
  {
    id: "w40",
    word: "bug",
    level: 1,
    phonetic: "bag",
    spanish: "Insecto / Bichito",
    synonyms: ["insect", "beetle", "bichito"],
    howToUseEs: "Usa 'bug' para nombrar animalitos diminutos como mariquitas u hormigas.",
    exampleEn: "A little green bug crawled on the leaf.",
    exampleEs: "Un pequeño bichito verde se arrastró en la hoja."
  },
  {
    id: "w41",
    word: "car",
    level: 1,
    phonetic: "kar",
    spanish: "Auto / Coche / Carro",
    synonyms: ["auto", "vehicle", "carrito"],
    howToUseEs: "Usa 'car' para el vehículo en el que vas con tu familia al colegio.",
    exampleEn: "We drive to school in our red car.",
    exampleEs: "Vamos a la escuela en nuestro auto rojo."
  },
  {
    id: "w42",
    word: "cap",
    level: 1,
    phonetic: "kap",
    spanish: "Gorra / Tapa",
    synonyms: ["hat", "visor", "gorrita"],
    howToUseEs: "Usa 'cap' para la gorra con visera de béisbol o la tapa del frasco.",
    exampleEn: "He puts his sports cap on.",
    exampleEs: "Él se pone su gorra deportiva."
  },
  {
    id: "w43",
    word: "arm",
    level: 1,
    phonetic: "arm",
    spanish: "Brazo",
    synonyms: ["limb", "bracito"],
    howToUseEs: "Usa 'arm' para la parte de tu cuerpo desde el hombro hasta la mano.",
    exampleEn: "Raise your right arm up.",
    exampleEs: "Levanta tu brazo derecho."
  },
  {
    id: "w44",
    word: "bow",
    level: 1,
    phonetic: "bou",
    spanish: "Moño / Arco",
    synonyms: ["ribbon", "knot", "moñito"],
    howToUseEs: "Usa 'bow' para un lindo adorno de cinta en la ropa o el arco de flechas.",
    exampleEn: "She wears a pink bow in her hair.",
    exampleEs: "Ella usa un moño rosa en su cabello."
  },

  // ==========================================
  // NIVEL 2: Objetos y Naturaleza (Palabras de 4-5 letras)
  // ==========================================
  {
    id: "w45",
    word: "apple",
    level: 2,
    phonetic: "á-pl",
    spanish: "Manzana",
    synonyms: ["fruit", "red fruit", "manzanita"],
    howToUseEs: "Usa 'apple' para describir una fruta jugosa roja o verde. Construye oraciones diciendo: 'An apple a day...' o 'I eat an apple'.",
    exampleEn: "I eat a sweet red apple every day.",
    exampleEs: "Como una dulce manzana roja todos los días."
  },
  {
    id: "w46",
    word: "baby",
    level: 2,
    phonetic: "béi-bi",
    spanish: "Bebé",
    synonyms: ["infant", "toddler", "bebecito"],
    howToUseEs: "Usa 'baby' para hablar de un niño o animal muy chiquito y tierno.",
    exampleEn: "The baby is sleeping softly.",
    exampleEs: "El bebé está durmiendo suavemente."
  },
  {
    id: "w47",
    word: "ball",
    level: 2,
    phonetic: "bol",
    spanish: "Pelota / Balón",
    synonyms: ["sphere", "orb", "pelotita"],
    howToUseEs: "Usa 'ball' cuando juegues al fútbol, baloncesto o a rebotar en el parque.",
    exampleEn: "Kick the blue ball to your friend.",
    exampleEs: "Patea la pelota azul a tu amigo."
  },
  {
    id: "w48",
    word: "banana",
    level: 2,
    phonetic: "ba-ná-na",
    spanish: "Plátano / Banano",
    synonyms: ["yellow fruit", "plantain", "bananita"],
    howToUseEs: "Usa 'banana' para la fruta amarilla favorita de los monos.",
    exampleEn: "The yellow banana tastes delicious.",
    exampleEs: "El plátano amarillo sabe delicioso."
  },
  {
    id: "w49",
    word: "belt",
    level: 2,
    phonetic: "belt",
    spanish: "Cinturón / Cinto",
    synonyms: ["strap", "girdle", "cinto"],
    howToUseEs: "Usa 'belt' para la correa de ajuste en tus pantalones.",
    exampleEn: "My black belt keeps my pants up.",
    exampleEs: "Mi cinturón negro sostiene mis pantalones."
  },
  {
    id: "w50",
    word: "blue",
    level: 2,
    phonetic: "blu",
    spanish: "Azul",
    synonyms: ["cyan", "azure", "azulito"],
    howToUseEs: "Usa 'blue' para pintar o describir el cielo brillante y el mar.",
    exampleEn: "The sky is bright blue today.",
    exampleEs: "El cielo está azul brillante hoy."
  },
  {
    id: "w51",
    word: "boat",
    level: 2,
    phonetic: "bout",
    spanish: "Barco / Bote",
    synonyms: ["ship", "vessel", "barquito"],
    howToUseEs: "Usa 'boat' para los vehículos que flotan y navegan en el agua.",
    exampleEn: "The white boat sails on the lake.",
    exampleEs: "El barco blanco navega en el lago."
  },
  {
    id: "w52",
    word: "book",
    level: 2,
    phonetic: "buk",
    spanish: "Libro",
    synonyms: ["novel", "storybook", "librito"],
    howToUseEs: "Usa 'book' cuando leas un cuento mágico o estudies para la escuela.",
    exampleEn: "I read a fun book before bedtime.",
    exampleEs: "Leo un libro divertido antes de dormir."
  },
  {
    id: "w53",
    word: "card",
    level: 2,
    phonetic: "kard",
    spanish: "Tarjeta / Carta",
    synonyms: ["postcard", "note", "tarjetita"],
    howToUseEs: "Usa 'card' cuando escribas un mensaje de cumpleaños o juegues a las cartas.",
    exampleEn: "I made a happy birthday card for dad.",
    exampleEs: "Hice una tarjeta de feliz cumpleaños para papá."
  },
  {
    id: "w54",
    word: "chair",
    level: 2,
    phonetic: "cher",
    spanish: "Silla",
    synonyms: ["seat", "armchair", "sillita"],
    howToUseEs: "Usa 'chair' cuando pidas a alguien que se siente a la mesa.",
    exampleEn: "Sit nicely on the wooden chair.",
    exampleEs: "Siéntate bonito en la silla de madera."
  },
  {
    id: "w55",
    word: "cold",
    level: 2,
    phonetic: "kold",
    spanish: "Frío",
    synonyms: ["chilly", "freezing", "friolento"],
    howToUseEs: "Usa 'cold' para describir el clima de invierno o un helado delicioso.",
    exampleEn: "Ice cream is very cold and tasty.",
    exampleEs: "El helado es muy frío y sabroso."
  },
  {
    id: "w56",
    word: "corn",
    level: 2,
    phonetic: "korn",
    spanish: "Maíz / Elote",
    synonyms: ["maize", "sweetcorn", "elotito"],
    howToUseEs: "Usa 'corn' para los granos amarillos sabrosos que comemos en palomitas o en la mazorca.",
    exampleEn: "We eat sweet corn at dinner.",
    exampleEs: "Comemos maíz dulce en la cena."
  },
  {
    id: "w57",
    word: "desk",
    level: 2,
    phonetic: "desk",
    spanish: "Escritorio / Pupitre",
    synonyms: ["table", "workspace", "pupitre"],
    howToUseEs: "Usa 'desk' para el mueble donde haces tu tarea en la escuela o en casa.",
    exampleEn: "My pencils are on top of my desk.",
    exampleEs: "Mis lápices están sobre mi escritorio."
  },
  {
    id: "w58",
    word: "doll",
    level: 2,
    phonetic: "dol",
    spanish: "Muñeca",
    synonyms: ["toy figure", "figure", "muñequita"],
    howToUseEs: "Usa 'doll' para hablar de tus muñecos de trapo o figuras de juguete.",
    exampleEn: "Her doll has a pretty blue dress.",
    exampleEs: "Su muñeca tiene un vestido azul lindo."
  },
  {
    id: "w59",
    word: "down",
    level: 2,
    phonetic: "daun",
    spanish: "Abajo / Hacia abajo",
    synonyms: ["below", "underneath", "abajo"],
    howToUseEs: "Usa 'down' para indicar una dirección descendente (ej: sit down, look down).",
    exampleEn: "Sit down on the rug, please.",
    exampleEs: "Siéntate abajo en la alfombra, por favor."
  },
  {
    id: "w60",
    word: "fast",
    level: 2,
    phonetic: "fast",
    spanish: "Rápido / Veloz",
    synonyms: ["quick", "speedy", "veloz"],
    howToUseEs: "Usa 'fast' cuando un auto o un corredor se mueva a gran velocidad.",
    exampleEn: "Cheetahs can run super fast.",
    exampleEs: "Los guepardos pueden correr súper rápido."
  },
  {
    id: "w61",
    word: "fish",
    level: 2,
    phonetic: "fish",
    spanish: "Pez / Pescado",
    synonyms: ["sea creature", "pececito"],
    howToUseEs: "Usa 'fish' para describir a las criaturitas marinas que nadan en el agua.",
    exampleEn: "The gold fish swims in the tank.",
    exampleEs: "El pez dorado nada en la pecera."
  },
  {
    id: "w62",
    word: "flag",
    level: 2,
    phonetic: "flag",
    spanish: "Bandera",
    synonyms: ["banner", "standard", "banderita"],
    howToUseEs: "Usa 'flag' para hablar de la bandera de tu país que ondea en el viento.",
    exampleEn: "The flag moves gently in the wind.",
    exampleEs: "La bandera se mueve suavemente con el viento."
  },
  {
    id: "w63",
    word: "frog",
    level: 2,
    phonetic: "frog",
    spanish: "Rana / Ranita",
    synonyms: ["toad", "amphibian", "ranita"],
    howToUseEs: "Usa 'frog' para el amigable animal verde que salta y dice 'ribbit'.",
    exampleEn: "The green frog hopped into the pond.",
    exampleEs: "La rana verde saltó al estanque."
  },
  {
    id: "w64",
    word: "game",
    level: 2,
    phonetic: "geim",
    spanish: "Juego",
    synonyms: ["sport", "playtime", "jueguito"],
    howToUseEs: "Usa 'game' para invitar a tus amigos a jugar algo divertido.",
    exampleEn: "Let us play a board game together.",
    exampleEs: "Juguemos un juego de mesa juntos."
  },
  {
    id: "w65",
    word: "gift",
    level: 2,
    phonetic: "gift",
    spanish: "Regalo / Obsequio",
    synonyms: ["present", "reward", "regalito"],
    howToUseEs: "Usa 'gift' cuando recibas una caja envuelta con un moño en la Navidad o cumpleaños.",
    exampleEn: "I got a lovely gift for my birthday.",
    exampleEs: "Recibí un regalo encantador para mi cumpleaños."
  },
  {
    id: "w66",
    word: "girl",
    level: 2,
    phonetic: "gurl",
    spanish: "Niña / Chicha",
    synonyms: ["female child", "young lady", "niñita"],
    howToUseEs: "Usa 'girl' para nombrar a una niña alegre y talentosa.",
    exampleEn: "The little girl is smiling warmly.",
    exampleEs: "La niñita está sonriendo con ternura."
  },
  {
    id: "w67",
    word: "hand",
    level: 2,
    phonetic: "jand",
    spanish: "Mano",
    synonyms: ["palm", "manita"],
    howToUseEs: "Usa 'hand' para la parte del cuerpo con la que aplaudes y saludas.",
    exampleEn: "Hold my hand to cross the street.",
    exampleEs: "Toma mi mano para cruzar la calle."
  },
  {
    id: "w68",
    word: "head",
    level: 2,
    phonetic: "jed",
    spanish: "Cabeza",
    synonyms: ["mind", "skull", "cabecita"],
    howToUseEs: "Usa 'head' para señalar la parte donde están tus pensamientos, cabello y sonrisa.",
    exampleEn: "Put your warm hat on your head.",
    exampleEs: "Pon tu gorro abrigador en tu cabeza."
  },
  {
    id: "w69",
    word: "kite",
    level: 2,
    phonetic: "kait",
    spanish: "Cometa / Papalote",
    synonyms: ["flyer", "papalote"],
    howToUseEs: "Usa 'kite' cuando vueles un juguete de colores alto en el parque en un día con viento.",
    exampleEn: "My diamond kite flies high up.",
    exampleEs: "Mi cometa voló súper alto."
  },
  {
    id: "w70",
    word: "moon",
    level: 2,
    phonetic: "mun",
    spanish: "Luna",
    synonyms: ["lunar star", "lunita"],
    howToUseEs: "Usa 'moon' para nombrar la hermosa luz blanca que vemos de noche en el cielo.",
    exampleEn: "The full moon shines brightly tonight.",
    exampleEs: "La luna llena brilla radiante esta noche."
  },
  {
    id: "w71",
    word: "neck",
    level: 2,
    phonetic: "nek",
    spanish: "Cuello",
    synonyms: ["throat", "cuellito"],
    howToUseEs: "Usa 'neck' para la parte donde te pones una bufanda calentita.",
    exampleEn: "Wear a soft scarf around your neck.",
    exampleEs: "Usa una bufanda suave alrededor de tu cuello."
  },
  {
    id: "w72",
    word: "nine",
    level: 2,
    phonetic: "nain",
    spanish: "Nueve (9)",
    synonyms: ["number 9"],
    howToUseEs: "Usa 'nine' para contar hasta el número 9.",
    exampleEn: "There are nine stars in the drawing.",
    exampleEs: "Hay nueve estrellas en el dibujo."
  },
  {
    id: "w73",
    word: "nose",
    level: 2,
    phonetic: "nous",
    spanish: "Nariz",
    synonyms: ["snout", "naricita"],
    howToUseEs: "Usa 'nose' para la parte de tu cara con la que hueles flores y deliciosos pasteles.",
    exampleEn: "The puppy touched my nose with its paw.",
    exampleEs: "El perrito tocó mi nariz con su pata."
  },
  {
    id: "w74",
    word: "pear",
    level: 2,
    phonetic: "per",
    spanish: "Pera",
    synonyms: ["green fruit", "perita"],
    howToUseEs: "Usa 'pear' para hablar de la jugosa fruta verde o amarilla con forma de gota.",
    exampleEn: "I love to eat a fresh green pear.",
    exampleEs: "Me encanta comer una pera verde fresca."
  },
  {
    id: "w75",
    word: "ring",
    level: 2,
    phonetic: "ring",
    spanish: "Anillo / Sonar",
    synonyms: ["band", "chime", "anillito"],
    howToUseEs: "Usa 'ring' para un anillo de adorno en los dedos o cuando suena el timbre de la escuela.",
    exampleEn: "Listen to the school bell ring!",
    exampleEs: "¡Escucha sonar el timbre de la escuela!"
  },
  {
    id: "w76",
    word: "star",
    level: 2,
    phonetic: "star",
    spanish: "Estrella",
    synonyms: ["sunlight dot", "estrellita"],
    howToUseEs: "Usa 'star' para las figuritas de cinco puntas o las luces lejanas del cielo nocturno.",
    exampleEn: "You get a gold star for doing great!",
    exampleEs: "¡Te ganaste una estrella dorada por hacerlo genial!"
  },
  {
    id: "w77",
    word: "tree",
    level: 2,
    phonetic: "tri",
    spanish: "Árbol",
    synonyms: ["plant", "wood tree", "arbolito"],
    howToUseEs: "Usa 'tree' para las plantas gigantes con ramas y hojas donde viven los pajaritos.",
    exampleEn: "Birds build nests high in the tree.",
    exampleEs: "Los pájaros hacen nidos alto en el árbol."
  },
  {
    id: "w78",
    word: "walk",
    level: 2,
    phonetic: "uok",
    spanish: "Caminar / Pasear",
    synonyms: ["stroll", "hike", "caminata"],
    howToUseEs: "Usa 'walk' para dar paseos tranquilos con tu familia y tus mascotas.",
    exampleEn: "We take a walk in the sunny park.",
    exampleEs: "Damos un paseo en el parque soleado."
  },
  {
    id: "w79",
    word: "wood",
    level: 2,
    phonetic: "wud",
    spanish: "Madera / Bosque",
    synonyms: ["timber", "forest", "maderita"],
    howToUseEs: "Usa 'wood' para el material duro con que se hacen mesas y lápices.",
    exampleEn: "This table is made of solid wood.",
    exampleEs: "Esta mesa está hecha de madera sólida."
  },
  {
    id: "w80",
    word: "year",
    level: 2,
    phonetic: "yir",
    spanish: "Año",
    synonyms: ["12 months", "annum"],
    howToUseEs: "Usa 'year' cuando celebres tu cumpleaños o desees feliz año nuevo.",
    exampleEn: "I am seven years old this year!",
    exampleEs: "¡Tengo siete años de edad este año!"
  },
  {
    id: "w81",
    word: "lamb",
    level: 2,
    phonetic: "lam",
    spanish: "Cordero / Corderito",
    synonyms: ["baby sheep", "corderito"],
    howToUseEs: "Usa 'lamb' para referirte al suave hijito blanco de la oveja.",
    exampleEn: "The little white lamb is very soft.",
    exampleEs: "El pequeño cordero blanco es muy suave."
  },
  {
    id: "w82",
    word: "milk",
    level: 2,
    phonetic: "milk",
    spanish: "Leche",
    synonyms: ["dairy drink", "lechecita"],
    howToUseEs: "Usa 'milk' para la bebida nutritiva blanca rica en calcio.",
    exampleEn: "Drink a glass of cold milk.",
    exampleEs: "Toma un vaso de leche fría."
  },

  // ==========================================
  // NIVEL 3: Acciones, Emociones y Familia (5-6 letras)
  // ==========================================
  {
    id: "w83",
    word: "black",
    level: 3,
    phonetic: "blak",
    spanish: "Negro",
    synonyms: ["dark", "ebony"],
    howToUseEs: "Usa 'black' para referirte a la noche sin luna o el color elegante del carbón.",
    exampleEn: "The cat has shiny black fur.",
    exampleEs: "El gato tiene pelaje negro brillante."
  },
  {
    id: "w84",
    word: "brown",
    level: 3,
    phonetic: "braun",
    spanish: "Marrón / Café",
    synonyms: ["brunette", "chocolate color"],
    howToUseEs: "Usa 'brown' para el color de los ositos de peluche o el delicioso chocolate.",
    exampleEn: "The teddy bear is warm brown.",
    exampleEs: "El oso de peluche es de color café cálido."
  },
  {
    id: "w85",
    word: "butter",
    level: 3,
    phonetic: "bá-ter",
    spanish: "Mantequilla",
    synonyms: ["spread", "mantequillita"],
    howToUseEs: "Usa 'butter' para lo que untamos sobre el tostado o los panqueques calientes.",
    exampleEn: "Put butter on your warm toast.",
    exampleEs: "Pon mantequilla en tu tostada caliente."
  },
  {
    id: "w86",
    word: "child",
    level: 3,
    phonetic: "chaild",
    spanish: "Niño / Niña / Hijo",
    synonyms: ["kid", "youngster", "pequeñín"],
    howToUseEs: "Usa 'child' para hablar de un pequeño amiguito o hijo amoroso.",
    exampleEn: "Every child likes to play games.",
    exampleEs: "A todo niño le gusta jugar juegos."
  },
  {
    id: "w87",
    word: "circle",
    level: 3,
    phonetic: "sér-kl",
    spanish: "Círculo / Redondel",
    synonyms: ["round shape", "ring"],
    howToUseEs: "Usa 'circle' para la figura geométrica redondita como una moneda o la luna llena.",
    exampleEn: "Draw a big round circle on paper.",
    exampleEs: "Dibuja un gran círculo redondo en el papel."
  },
  {
    id: "w88",
    word: "cloudy",
    level: 3,
    phonetic: "kláu-di",
    spanish: "Nublado",
    synonyms: ["overcast", "hazy"],
    howToUseEs: "Usa 'cloudy' para describir un día con muchas nubes esponjosas en el cielo.",
    exampleEn: "It is a cloudy and cool day.",
    exampleEs: "Es un día nublado y fresco."
  },
  {
    id: "w89",
    word: "color",
    level: 3,
    phonetic: "ká-lor",
    spanish: "Color / Colorear",
    synonyms: ["shade", "hue", "colorcito"],
    howToUseEs: "Usa 'color' para hablar del rojo, azul, verde y todos los tonos del arcoíris.",
    exampleEn: "What is your favorite bright color?",
    exampleEs: "¿Cuál es tu color brillante favorito?"
  },
  {
    id: "w90",
    word: "cookies",
    level: 3,
    phonetic: "kú-kis",
    spanish: "Galletas",
    synonyms: ["biscuits", "treats", "galletitas"],
    howToUseEs: "Usa 'cookies' para los postres crujientes con chispas de chocolate.",
    exampleEn: "Grandma bakes chocolate chip cookies.",
    exampleEs: "La abuela hornea galletas con chispas de chocolate."
  },
  {
    id: "w91",
    word: "count",
    level: 3,
    phonetic: "kaunt",
    spanish: "Contar (números)",
    synonyms: ["calculate", "tally", "numerar"],
    howToUseEs: "Usa 'count' cuando cuentes 1, 2, 3... las estrellas o juguetes.",
    exampleEn: "Can you count from one to ten?",
    exampleEs: "¿Puedes contar del uno al diez?"
  },
  {
    id: "w92",
    word: "crayon",
    level: 3,
    phonetic: "kréi-on",
    spanish: "Crayón / Lápiz de cera",
    synonyms: ["wax pencil", "crayoncito"],
    howToUseEs: "Usa 'crayon' para tus barras de cera de colores para pintar dibujos.",
    exampleEn: "Pick a blue crayon to color the sea.",
    exampleEs: "Elige un crayón azul para colorear el mar."
  },
  {
    id: "w93",
    word: "dress",
    level: 3,
    phonetic: "dres",
    spanish: "Vestido / Vestirse",
    synonyms: ["gown", "attire", "vestidito"],
    howToUseEs: "Usa 'dress' para la linda prenda de vestir de una pieza o la acción de vestirse.",
    exampleEn: "She wore a yellow dress to the party.",
    exampleEs: "Ella usó un vestido amarillo para la fiesta."
  },
  {
    id: "w94",
    word: "eight",
    level: 3,
    phonetic: "eit",
    spanish: "Ocho (8)",
    synonyms: ["number 8"],
    howToUseEs: "Usa 'eight' para decir el número 8 en inglés.",
    exampleEn: "An octopus has eight legs.",
    exampleEs: "Un pulpo tiene ocho patas."
  },
  {
    id: "w95",
    word: "father",
    level: 3,
    phonetic: "fá-der",
    spanish: "Padre / Papá",
    synonyms: ["dad", "daddy", "papi"],
    howToUseEs: "Usa 'father' para referirte con respeto y amor a tu papá.",
    exampleEn: "My father helps me with homework.",
    exampleEs: "Mi padre me ayuda con la tarea."
  },
  {
    id: "w96",
    word: "finish",
    level: 3,
    phonetic: "fí-nish",
    spanish: "Terminar / Finalizar",
    synonyms: ["complete", "end", "concluir"],
    howToUseEs: "Usa 'finish' cuando completes una tarea o llegues a la meta de una carrera.",
    exampleEn: "Finish your meal before playing.",
    exampleEs: "Termina tu comida antes de jugar."
  },
  {
    id: "w97",
    word: "flower",
    level: 3,
    phonetic: "fláu-er",
    spanish: "Flor / Florcita",
    synonyms: ["blossom", "bloom", "florcita"],
    howToUseEs: "Usa 'flower' para las plantas hermosas que huelen bien en el jardín.",
    exampleEn: "The red flower smells so sweet.",
    exampleEs: "La flor roja huele muy dulce."
  },
  {
    id: "w98",
    word: "friend",
    level: 3,
    phonetic: "frend",
    spanish: "Amigo / Amiga",
    synonyms: ["pal", "buddy", "amiguito"],
    howToUseEs: "Usa 'friend' para tus compañeros preferidos con quienes juegas y compartes.",
    exampleEn: "You are my best friend!",
    exampleEs: "¡Tú eres mi mejor amigo!"
  },
  {
    id: "w99",
    word: "fruit",
    level: 3,
    phonetic: "frut",
    spanish: "Fruta",
    synonyms: ["fresh food", "frutita"],
    howToUseEs: "Usa 'fruit' para alimentos naturales deliciosos como manzanas, fresas y uvas.",
    exampleEn: "Fresh fruit is healthy for kids.",
    exampleEs: "La fruta fresca es saludable para los niños."
  },
  {
    id: "w100",
    word: "green",
    level: 3,
    phonetic: "grin",
    spanish: "Verde",
    synonyms: ["emerald", "verdoso"],
    howToUseEs: "Usa 'green' para el color del césped, las hojas y las ranas.",
    exampleEn: "Leaves turn bright green in spring.",
    exampleEs: "Las hojas se vuelven verde brillante en primavera."
  },
  {
    id: "w101",
    word: "happy",
    level: 3,
    phonetic: "já-pi",
    spanish: "Feliz / Alegre",
    synonyms: ["joyful", "cheerful", "contento"],
    howToUseEs: "Usa 'happy' para expresar alegría y sonreír. ¡I am happy!",
    exampleEn: "We are very happy today.",
    exampleEs: "Estamos muy felices hoy."
  },
  {
    id: "w102",
    word: "house",
    level: 3,
    phonetic: "jaus",
    spanish: "Casa / Hogar",
    synonyms: ["home", "residence", "casita"],
    howToUseEs: "Usa 'house' para hablar del lugar donde vives acogido con tu familia.",
    exampleEn: "Our house has a garden in front.",
    exampleEs: "Nuestra casa tiene un jardín al frente."
  },
  {
    id: "w103",
    word: "igloo",
    level: 3,
    phonetic: "íg-lu",
    spanish: "Iglú",
    synonyms: ["snow house", "ice dome"],
    howToUseEs: "Usa 'igloo' para la famosa casita redonda hecha de bloques de nieve.",
    exampleEn: "An igloo is built from ice blocks.",
    exampleEs: "Un iglú se construye con bloques de hielo."
  },
  {
    id: "w104",
    word: "jelly",
    level: 3,
    phonetic: "djé-li",
    spanish: "Gelatina / Mermelada",
    synonyms: ["jam", "gelatin", "gelatinita"],
    howToUseEs: "Usa 'jelly' para el postre suave y tembloroso de frutas.",
    exampleEn: "I love peanut butter and jelly sandwiches.",
    exampleEs: "Me encantan los sándwiches de mantequilla de maní y gelatina."
  },
  {
    id: "w105",
    word: "knees",
    level: 3,
    phonetic: "nis",
    spanish: "Rodillas",
    synonyms: ["leg joints", "rodillitas"],
    howToUseEs: "Usa 'knees' para la articulación en medio de tus piernas.",
    exampleEn: "Bend your knees to jump high.",
    exampleEs: "Dobla tus rodillas para saltar alto."
  },
  {
    id: "w106",
    word: "lemon",
    level: 3,
    phonetic: "lé-mon",
    spanish: "Limón",
    synonyms: ["citrus fruit", "limoncito"],
    howToUseEs: "Usa 'lemon' para la fruta ácida y amarilla ideal para limonada.",
    exampleEn: "A lemon makes fresh lemonade.",
    exampleEs: "Un limón hace limonada fresca."
  },
  {
    id: "w107",
    word: "night",
    level: 3,
    phonetic: "nait",
    spanish: "Noche",
    synonyms: ["darkness", "nighttime", "nochecita"],
    howToUseEs: "Usa 'night' cuando el sol se oculta y salen las estrellas para dormir.",
    exampleEn: "Say good night before going to bed.",
    exampleEs: "Di buenas noches antes de ir a la cama."
  },
  {
    id: "w108",
    word: "sister",
    level: 3,
    phonetic: "sís-ter",
    spanish: "Hermana",
    synonyms: ["sibling", "hermanita"],
    howToUseEs: "Usa 'sister' para nombrar a tu hermana con cariño.",
    exampleEn: "My sister plays with me.",
    exampleEs: "Mi hermana juega conmigo."
  },
  {
    id: "w109",
    word: "sleep",
    level: 3,
    phonetic: "slip",
    spanish: "Dormir",
    synonyms: ["slumber", "rest", "soñar"],
    howToUseEs: "Usa 'sleep' para descansar tus ojitos durante la noche.",
    exampleEn: "I sleep eight hours every night.",
    exampleEs: "Duermo ocho horas cada noche."
  },
  {
    id: "w110",
    word: "train",
    level: 3,
    phonetic: "trein",
    spanish: "Tren / Ferrocarril",
    synonyms: ["locomotive", "railway", "trencito"],
    howToUseEs: "Usa 'train' para los vehículos de muchos vagones que van sobre rieles 'choo-choo'.",
    exampleEn: "The train moves fast on the tracks.",
    exampleEs: "El tren se mueve rápido en las vías."
  },
  {
    id: "w111",
    word: "water",
    level: 3,
    phonetic: "uó-ter",
    spanish: "Agua",
    synonyms: ["liquid", "h2o", "agüita"],
    howToUseEs: "Usa 'water' para el líquido vital cristalino que bebemos para estar sanos.",
    exampleEn: "Drink fresh water after running.",
    exampleEs: "Toma agua fresca después de correr."
  },
  {
    id: "w112",
    word: "furry",
    level: 3,
    phonetic: "fér-i",
    spanish: "Peludito / Esponjoso",
    synonyms: ["fluffy", "hairy", "peludito"],
    howToUseEs: "Usa 'furry' para describir el pelaje suave de un gatito o perrito.",
    exampleEn: "The furry cat purrs softly.",
    exampleEs: "El gato peludito ronronea suavemente."
  },
  {
    id: "w113",
    word: "ghost",
    level: 3,
    phonetic: "goust",
    spanish: "Fantasma",
    synonyms: ["spirit", "phantom", "fantasmito"],
    howToUseEs: "Usa 'ghost' para personajes divertidos de disfraces en Halloween que dicen 'boo'.",
    exampleEn: "The friendly ghost says boo!",
    exampleEs: "¡El fantasma amigable dice boo!"
  },
  {
    id: "w114",
    word: "hard",
    level: 3,
    phonetic: "jard",
    spanish: "Duro / Difícil",
    synonyms: ["solid", "tough", "fuerte"],
    howToUseEs: "Usa 'hard' para una piedra resistente o algo que requiere mucho esfuerzo.",
    exampleEn: "A diamond is very hard.",
    exampleEs: "Un diamante es muy duro."
  },
  {
    id: "w115",
    word: "hello",
    level: 3,
    phonetic: "je-lóu",
    spanish: "Hola",
    synonyms: ["hi", "greetings", "saluditos"],
    howToUseEs: "Usa 'hello' para saludar cordialmente a tus amigos y profesores.",
    exampleEn: "Say hello when you meet someone.",
    exampleEs: "Di hola cuando conozcas a alguien."
  },
  {
    id: "w116",
    word: "jacket",
    level: 3,
    phonetic: "djar-ket",
    spanish: "Chaqueta / Chamarra",
    synonyms: ["coat", "windbreaker", "chamarrita"],
    howToUseEs: "Usa 'jacket' cuando te pongas tu abrigo para salir al frío.",
    exampleEn: "Zip up your jacket before going out.",
    exampleEs: "Súbete el cierre de la chaqueta antes de salir."
  },
  {
    id: "w117",
    word: "Friday",
    level: 3,
    phonetic: "frái-dei",
    spanish: "Viernes",
    synonyms: ["end of school week"],
    howToUseEs: "Usa 'Friday' para nombrar el quinto día de la semana escolar.",
    exampleEn: "Friday is my favorite school day.",
    exampleEs: "El viernes es mi día escolar favorito."
  },
  {
    id: "w118",
    word: "hot dog",
    level: 3,
    phonetic: "jot dog",
    spanish: "Perro caliente / Pancho",
    synonyms: ["frankfurter", "sausage roll"],
    howToUseEs: "Usa 'hot dog' para la deliciosa salchicha en pan para paseos.",
    exampleEn: "I ate a hot dog at the park.",
    exampleEs: "Comí un perro caliente en el parque."
  },
  {
    id: "w119",
    word: "January",
    level: 3,
    phonetic: "djá-nu-a-ri",
    spanish: "Enero",
    synonyms: ["first month"],
    howToUseEs: "Usa 'January' para nombrar el primer mes del año donde llega el año nuevo.",
    exampleEn: "January is the first month of the year.",
    exampleEs: "Enero es el primer mes del año."
  },
  {
    id: "w120",
    word: "July",
    level: 3,
    phonetic: "dju-lái",
    spanish: "Julio",
    synonyms: ["seventh month"],
    howToUseEs: "Usa 'July' para nombrar el mes veraniego de vacaciones y sol.",
    exampleEn: "July brings hot sunny weather.",
    exampleEs: "Julio trae clima caluroso y soleado."
  },
  {
    id: "w121",
    word: "June",
    level: 3,
    phonetic: "djun",
    spanish: "Junio",
    synonyms: ["sixth month"],
    howToUseEs: "Usa 'June' para el mes del inicio de las vacaciones de verano.",
    exampleEn: "School finishes in June.",
    exampleEs: "La escuela termina en junio."
  },
  {
    id: "w122",
    word: "March",
    level: 3,
    phonetic: "march",
    spanish: "Marzo",
    synonyms: ["third month"],
    howToUseEs: "Usa 'March' para el mes en que comienza la hermosa primavera.",
    exampleEn: "Flowers bloom in March.",
    exampleEs: "Las flores florecen en marzo."
  },
  {
    id: "w123",
    word: "May",
    level: 3,
    phonetic: "mei",
    spanish: "Mayo",
    synonyms: ["fifth month"],
    howToUseEs: "Usa 'May' para nombrar el quinto mes del año lleno de sol.",
    exampleEn: "Mother's day is celebrated in May.",
    exampleEs: "El día de las madres se celebra en mayo."
  },
  {
    id: "w124",
    word: "Monday",
    level: 3,
    phonetic: "mán-dei",
    spanish: "Lunes",
    synonyms: ["start of school week"],
    howToUseEs: "Usa 'Monday' para el primer día de la semana escolar.",
    exampleEn: "We start school on Monday morning.",
    exampleEs: "Empezamos la escuela el lunes por la mañana."
  },

  // ==========================================
  // NIVEL 4: Escuela, Entorno y Objetos (6-7 letras)
  // ==========================================
  {
    id: "w125",
    word: "bedroom",
    level: 4,
    phonetic: "béd-rum",
    spanish: "Habitación / Cuarto",
    synonyms: ["room", "chamber", "recámara"],
    howToUseEs: "Usa 'bedroom' para referirte a tu lindo cuarto donde está tu cama y juguetes.",
    exampleEn: "My bedroom is cozy and neat.",
    exampleEs: "Mi habitación es acogedora y ordenada."
  },
  {
    id: "w126",
    word: "kitchen",
    level: 4,
    phonetic: "kí-chen",
    spanish: "Cocina",
    synonyms: ["cooking room", "galley"],
    howToUseEs: "Usa 'kitchen' para el lugar de la casa donde se prepara la comida sabrosa.",
    exampleEn: "Mom is baking cookies in the kitchen.",
    exampleEs: "Mamá está horneando galletas en la cocina."
  },
  {
    id: "w127",
    word: "mailman",
    level: 4,
    phonetic: "méil-man",
    spanish: "Cartero",
    synonyms: ["postman", "courier", "carterito"],
    howToUseEs: "Usa 'mailman' para la persona amable que entrega las cartas y paquetes en tu hogar.",
    exampleEn: "The mailman delivered a letter today.",
    exampleEs: "El cartero entregó una carta hoy."
  },
  {
    id: "w128",
    word: "monkey",
    level: 4,
    phonetic: "mán-ki",
    spanish: "Mono / Monito",
    synonyms: ["primate", "chimp", "monito"],
    howToUseEs: "Usa 'monkey' para el divertido animal que salta entre ramas y come plátanos.",
    exampleEn: "The funny monkey swings on branches.",
    exampleEs: "El mono divertido se mece en las ramas."
  },
  {
    id: "w129",
    word: "picture",
    level: 4,
    phonetic: "pík-chur",
    spanish: "Imagen / Foto / Dibujo",
    synonyms: ["photo", "drawing", "dibujito"],
    howToUseEs: "Usa 'picture' cuando dibujes una obra de arte o tomes una fotografía.",
    exampleEn: "I drew a colorful picture of my family.",
    exampleEs: "Dibujé una imagen colorida de mi familia."
  },
  {
    id: "w130",
    word: "rabbit",
    level: 4,
    phonetic: "rá-bit",
    spanish: "Conejo / Conejito",
    synonyms: ["bunny", "hare", "conejito"],
    howToUseEs: "Usa 'rabbit' para el animal de orejas largas que salta y come zanahorias.",
    exampleEn: "The fluffy rabbit chews a fresh carrot.",
    exampleEs: "El conejo esponjoso muerde una zanahoria fresca."
  },
  {
    id: "w131",
    word: "school",
    level: 4,
    phonetic: "skul",
    spanish: "Escuela / Colegio",
    synonyms: ["academy", "colegio", "escuelita"],
    howToUseEs: "Usa 'school' para el lugar grandioso donde aprendes, juegas y tienes amigos.",
    exampleEn: "I love to learn new things at school.",
    exampleEs: "Me encanta aprender cosas nuevas en la escuela."
  },
  {
    id: "w132",
    word: "sweater",
    level: 4,
    phonetic: "sué-ter",
    spanish: "Suéter / Abrigo de lana",
    synonyms: ["jumper", "pullover", "suetercito"],
    howToUseEs: "Usa 'sweater' para la prenda suave de lana que te abriga en los días fríos.",
    exampleEn: "Wear a warm sweater on chilly days.",
    exampleEs: "Usa un suéter abrigador en días fríos."
  },
  {
    id: "w133",
    word: "teacher",
    level: 4,
    phonetic: "tí-cher",
    spanish: "Profesor / Maestro",
    synonyms: ["instructor", "educator", "maestrito"],
    howToUseEs: "Usa 'teacher' para nombrar a tu maestra o maestro con mucho respeto.",
    exampleEn: "Our teacher explains lessons clearly.",
    exampleEs: "Nuestro profesor explica las lecciones con claridad."
  },
  {
    id: "w134",
    word: "weather",
    level: 4,
    phonetic: "ué-der",
    spanish: "Clima / Tiempo atmosférico",
    synonyms: ["climate", "atmosphere", "climita"],
    howToUseEs: "Usa 'weather' para hablar de si el día está soleado, lluvioso o con viento.",
    exampleEn: "The weather today is warm and bright.",
    exampleEs: "El clima de hoy es cálido y brillante."
  },
  {
    id: "w135",
    word: "yellow",
    level: 4,
    phonetic: "yé-lou",
    spanish: "Amarillo",
    synonyms: ["golden", "amber", "amarillito"],
    howToUseEs: "Usa 'yellow' para el color radiante del sol, los plátanos y los girasoles.",
    exampleEn: "The sun is a big yellow star.",
    exampleEs: "El sol es una gran estrella amarilla."
  },
  {
    id: "w136",
    word: "canyon",
    level: 4,
    phonetic: "ká-nyon",
    spanish: "Cañón (Geografía)",
    synonyms: ["gorge", "ravine"],
    howToUseEs: "Usa 'canyon' para hablar de un gran valle profundo entre montañas de piedra.",
    exampleEn: "The Grand Canyon is giant and famous.",
    exampleEs: "El Gran Cañón es gigante y famoso."
  },
  {
    id: "w137",
    word: "fireman",
    level: 4,
    phonetic: "fái-er-man",
    spanish: "Bombero",
    synonyms: ["firefighter", "hero"],
    howToUseEs: "Usa 'fireman' para referirte al héroe que apaga incendios y ayuda en emergencias.",
    exampleEn: "The brave fireman drives a big red truck.",
    exampleEs: "El valiente bombero conduce un camión rojo grande."
  },
  {
    id: "w138",
    word: "person",
    level: 4,
    phonetic: "pér-son",
    spanish: "Persona / Ser humano",
    synonyms: ["human", "individual"],
    howToUseEs: "Usa 'person' para hablar de cualquier hombre, mujer, niño o niña.",
    exampleEn: "She is a very kind person.",
    exampleEs: "Ella es una persona muy amable."
  },
  {
    id: "w139",
    word: "plant",
    level: 4,
    phonetic: "plant",
    spanish: "Planta / Plantar",
    synonyms: ["flora", "vegetation", "plantita"],
    howToUseEs: "Usa 'plant' para las hojitas verdes del jardín o la acción de sembrar semillas.",
    exampleEn: "Water the green plant every day.",
    exampleEs: "Riega la planta verde todos los días."
  },
  {
    id: "w140",
    word: "plate",
    level: 4,
    phonetic: "pleit",
    spanish: "Plato",
    synonyms: ["dish", "platter", "platito"],
    howToUseEs: "Usa 'plate' para el recipiente llano donde te sirven la comida.",
    exampleEn: "Put the sandwich on your blue plate.",
    exampleEs: "Pon el sándwich en tu plato azul."
  },
  {
    id: "w141",
    word: "quack",
    level: 4,
    phonetic: "kuak",
    spanish: "Cua-cua (Sonido de pato)",
    synonyms: ["duck sound"],
    howToUseEs: "Usa 'quack' para imitar el divertido graznido de los patos.",
    exampleEn: "The little duck says quack quack!",
    exampleEs: "¡El patito dice cua cua!"
  },
  {
    id: "w142",
    word: "queen",
    level: 4,
    phonetic: "kuin",
    spanish: "Reina",
    synonyms: ["royal lady", "monarch"],
    howToUseEs: "Usa 'queen' para la dama real que lleva una hermosa corona brillante.",
    exampleEn: "The queen wears a shiny golden crown.",
    exampleEs: "La reina usa una brillante corona de oro."
  },
  {
    id: "w143",
    word: "rainy",
    level: 4,
    phonetic: "réi-ni",
    spanish: "Lluvioso",
    synonyms: ["wet weather", "showery"],
    howToUseEs: "Usa 'rainy' cuando caiga lluvia del cielo y necesites tu paraguas.",
    exampleEn: "Take an umbrella on a rainy day.",
    exampleEs: "Lleva un paraguas en un día lluvioso."
  },
  {
    id: "w144",
    word: "robot",
    level: 4,
    phonetic: "róu-bot",
    spanish: "Robot / Autómata",
    synonyms: ["bot", "android", "robotín"],
    howToUseEs: "Usa 'robot' para los increíbles juguetes metálicos inteligentes.",
    exampleEn: "My toy robot can walk and blink lights.",
    exampleEs: "Mi robot de juguete puede caminar y parpadear luces."
  },
  {
    id: "w145",
    word: "ruler",
    level: 4,
    phonetic: "rú-ler",
    spanish: "Regla (escolar)",
    synonyms: ["measuring stick", "reglita"],
    howToUseEs: "Usa 'ruler' para el útil escolar con números para trazar líneas rectas.",
    exampleEn: "Use a ruler to draw a straight line.",
    exampleEs: "Usa una regla para dibujar una línea recta."
  },
  {
    id: "w146",
    word: "salad",
    level: 4,
    phonetic: "sá-lad",
    spanish: "Ensalada",
    synonyms: ["greens", "salad dish"],
    howToUseEs: "Usa 'salad' para el plato nutritivo de lechuga, tomate y verduras.",
    exampleEn: "Fresh salad is good for health.",
    exampleEs: "La ensalada fresca es buena para la salud."
  },
  {
    id: "w147",
    word: "scarf",
    level: 4,
    phonetic: "skarf",
    spanish: "Bufanda",
    synonyms: ["muffler", "wrap", "bufandita"],
    howToUseEs: "Usa 'scarf' para la prenda abrigadora que envuelve tu cuello en invierno.",
    exampleEn: "Wrap a warm scarf around your neck.",
    exampleEs: "Envuelve una bufanda abrigadora en tu cuello."
  },
  {
    id: "w148",
    word: "shoes",
    level: 4,
    phonetic: "shus",
    spanish: "Zapatos / Calzado",
    synonyms: ["footwear", "sneakers", "zapatitos"],
    howToUseEs: "Usa 'shoes' para el calzado cómodo que te pones antes de correr al parque.",
    exampleEn: "Tie the laces of your red shoes.",
    exampleEs: "Ata las agujetas de tus zapatos rojos."
  },
  {
    id: "w149",
    word: "skirt",
    level: 4,
    phonetic: "skert",
    spanish: "Falda",
    synonyms: ["dress skirt", "faldita"],
    howToUseEs: "Usa 'skirt' para describir esta prenda de vestir escolar o de fiesta.",
    exampleEn: "She wore a pleated blue skirt.",
    exampleEs: "Ella usó una falda azul con pliegues."
  },
  {
    id: "w150",
    word: "socks",
    level: 4,
    phonetic: "soks",
    spanish: "Calcetines / Medias",
    synonyms: ["stockings", "calcetinitos"],
    howToUseEs: "Usa 'socks' para las prendas suaves que cubren tus pies dentro de los zapatos.",
    exampleEn: "I wear warm white socks.",
    exampleEs: "Uso calcetines blancos y abrigadores."
  },
  {
    id: "w151",
    word: "sport",
    level: 4,
    phonetic: "sport",
    spanish: "Deporte",
    synonyms: ["game", "athletics", "deportes"],
    howToUseEs: "Usa 'sport' cuando juegues fútbol, natación o carreras de atletismo.",
    exampleEn: "Soccer is a fun team sport.",
    exampleEs: "El fútbol es un divertido deporte en equipo."
  },
  {
    id: "w152",
    word: "storm",
    level: 4,
    phonetic: "storm",
    spanish: "Tormenta",
    synonyms: ["tempest", "gale", "tormentita"],
    howToUseEs: "Usa 'storm' cuando el cielo tenga truenos, relámpagos y lluvia fuerte.",
    exampleEn: "We stayed inside during the rain storm.",
    exampleEs: "Nos quedamos adentro durante la tormenta de lluvia."
  },
  {
    id: "w153",
    word: "story",
    level: 4,
    phonetic: "stó-ri",
    spanish: "Historia / Cuento",
    synonyms: ["tale", "fable", "cuentito"],
    howToUseEs: "Usa 'story' cuando papá o mamá te lean un lindo cuento antes de dormir.",
    exampleEn: "Tell me a bedtime story please.",
    exampleEs: "Cuéntame un cuento de buenas noches por favor."
  },
  {
    id: "w154",
    word: "swing",
    level: 4,
    phonetic: "suing",
    spanish: "Columpio / Columpiarse",
    synonyms: ["sway", "glider", "columpito"],
    howToUseEs: "Usa 'swing' para los juegos del parque donde te meces alto hacia las nubes.",
    exampleEn: "I swing high at the playground.",
    exampleEs: "Me columpio alto en el parque infantil."
  },

  // ==========================================
  // NIVEL 5: Super Campeón Spelling Bee (Palabras largas o tramposas)
  // ==========================================
  {
    id: "w155",
    word: "scissors",
    level: 5,
    phonetic: "sí-sors",
    spanish: "Tijeras",
    synonyms: ["clippers", "shearers", "tijeritas"],
    howToUseEs: "¡Atención Spelling Bee! 'Scissors' tiene doble 's' y una 'c' muda al inicio. Usa 'scissors' para recortar papeles de colores.",
    exampleEn: "Cut the red paper with safety scissors.",
    exampleEs: "Corta el papel rojo con tijeras de seguridad."
  },
  {
    id: "w156",
    word: "umbrella",
    level: 5,
    phonetic: "am-bré-la",
    spanish: "Paraguas / Sombrilla",
    synonyms: ["parasol", "rain shade", "paragüitas"],
    howToUseEs: "¡Palabra de campeón! 'Umbrella' se escribe con doble 'l'. Úsala para protegerte de las gotas de lluvia.",
    exampleEn: "Open your yellow umbrella when it rains.",
    exampleEs: "Abre tu paraguas amarillo cuando llueva."
  },
  {
    id: "w157",
    word: "shoulder",
    level: 5,
    phonetic: "shóul-der",
    spanish: "Hombro",
    synonyms: ["shoulder joint", "hombrito"],
    howToUseEs: "Usa 'shoulder' para la parte donde se unen tus brazos al tronco del cuerpo.",
    exampleEn: "Tap me on the shoulder to call me.",
    exampleEs: "Tócame en el hombro para llamarme."
  },
  {
    id: "w158",
    word: "Tuesday",
    level: 5,
    phonetic: "tiús-dei",
    spanish: "Martes",
    synonyms: ["second school day"],
    howToUseEs: "¡Recuerda escribir la 'T' mayúscula! 'Tuesday' es el segundo día de la semana de clases.",
    exampleEn: "We have music class on Tuesday.",
    exampleEs: "Tenemos clase de música el martes."
  },
  {
    id: "w159",
    word: "twelve",
    level: 5,
    phonetic: "tuelv",
    spanish: "Doce (12)",
    synonyms: ["number 12", "dozen"],
    howToUseEs: "Usa 'twelve' para el número 12 o para contar una docena de huevos.",
    exampleEn: "There are twelve months in one year.",
    exampleEs: "Hay doce meses en un año."
  },
  {
    id: "w160",
    word: "twenty",
    level: 5,
    phonetic: "tuén-ti",
    spanish: "Veinte (20)",
    synonyms: ["number 20"],
    howToUseEs: "Usa 'twenty' para el número 20 en inglés.",
    exampleEn: "I counted twenty stars in the picture.",
    exampleEs: "Conté veinte estrellas en la imagen."
  },
  {
    id: "w161",
    word: "tongue",
    level: 5,
    phonetic: "tang",
    spanish: "Lengua",
    synonyms: ["taste organ", "lenguita"],
    howToUseEs: "¡Cuidado con la ortografía! Termina en 'gue'. Usa 'tongue' para saborear un rico helado.",
    exampleEn: "Taste the cool ice cream with your tongue.",
    exampleEs: "Saborea el rico helado con tu lengua."
  },
  {
    id: "w162",
    word: "zebra",
    level: 5,
    phonetic: "sí-bra",
    spanish: "Cebra",
    synonyms: ["striped horse", "cebrita"],
    howToUseEs: "Usa 'zebra' para el asombroso animal de la sabana cubierto de rayas negras y blancas.",
    exampleEn: "The zebra has black and white stripes.",
    exampleEs: "La cebra tiene rayas negras y blancas."
  },
  {
    id: "w163",
    word: "yo-yo",
    level: 5,
    phonetic: "yó-yo",
    spanish: "Yoyo",
    synonyms: ["string toy", "yoyito"],
    howToUseEs: "Usa 'yo-yo' para el divertido juguete de cordón que sube y baja.",
    exampleEn: "I can spin my yo-yo up and down.",
    exampleEs: "Puedo hacer girar mi yoyo arriba y abajo."
  },
  {
    id: "w164",
    word: "autumn",
    level: 5,
    phonetic: "ó-tom",
    spanish: "Otoño",
    synonyms: ["fall", "harvest season"],
    howToUseEs: "¡Ojo con la 'mn' final silenciosa! 'Autumn' es la estación dorada en que caen las hojas secas de los árboles.",
    exampleEn: "Leaves turn orange and fall in autumn.",
    exampleEs: "Las hojas se vuelven naranjas y caen en otoño."
  },
  {
    id: "w165",
    word: "window",
    level: 5,
    phonetic: "uín-dou",
    spanish: "Ventana",
    synonyms: ["pane", "casement", "ventanita"],
    howToUseEs: "Usa 'window' para el cristal de la casa por donde entra la luz del sol.",
    exampleEn: "Look out the window to see the birds.",
    exampleEs: "Mira por la ventana para ver los pájaros."
  },
  {
    id: "w166",
    word: "windy",
    level: 5,
    phonetic: "uín-di",
    spanish: "Ventoso / Con mucho viento",
    synonyms: ["breezy", "blustery"],
    howToUseEs: "Usa 'windy' en un día fantástico para salir a volar cometas.",
    exampleEn: "It is very windy, fly your kite!",
    exampleEs: "¡Está muy ventoso, vuela tu cometa!"
  },
  {
    id: "w167",
    word: "woman",
    level: 5,
    phonetic: "uú-man",
    spanish: "Mujer / Señora",
    synonyms: ["lady", "adult female", "señora"],
    howToUseEs: "Usa 'woman' para referirte a una dama como mamá, la abuela o tu maestra.",
    exampleEn: "The polite woman smiled at us.",
    exampleEs: "La amable mujer nos sonrió."
  },
  {
    id: "w168",
    word: "April",
    level: 5,
    phonetic: "éi-pril",
    spanish: "Abril",
    synonyms: ["fourth month"],
    howToUseEs: "Usa 'April' con A mayúscula para el cuarto mes del año lleno de flores.",
    exampleEn: "April showers bring May flowers.",
    exampleEs: "Las lluvias de abril traen las flores de mayo."
  },
  {
    id: "w169",
    word: "August",
    level: 5,
    phonetic: "ó-gost",
    spanish: "Agosto",
    synonyms: ["eighth month"],
    howToUseEs: "Usa 'August' para el octavo mes del año en medio de las vacaciones de verano.",
    exampleEn: "We go to the beach in August.",
    exampleEs: "Vamos a la playa en agosto."
  },
  {
    id: "w170",
    word: "blouse",
    level: 5,
    phonetic: "blaus",
    spanish: "Blusa",
    synonyms: ["shirt", "top", "blusita"],
    howToUseEs: "Usa 'blouse' para la camisa fina femenina.",
    exampleEn: "Mom wore a nice silk blouse.",
    exampleEs: "Mamá usó una linda blusa de seda."
  },
  {
    id: "w171",
    word: "closed",
    level: 5,
    phonetic: "klousd",
    spanish: "Cerrado",
    synonyms: ["shut", "locked", "cerradito"],
    howToUseEs: "Usa 'closed' cuando una puerta, tienda o libro esté cerrado.",
    exampleEn: "The toy store is closed for today.",
    exampleEs: "La tienda de juguetes está cerrada por hoy."
  },
  {
    id: "w172",
    word: "evening",
    level: 5,
    phonetic: "ív-ning",
    spanish: "Tarde-Noche / Atardecer",
    synonyms: ["dusk", "nightfall"],
    howToUseEs: "Usa 'evening' para el momento en que el sol baja antes de ir a cenar.",
    exampleEn: "Good evening everyone!",
    exampleEs: "¡Buenas tardes a todos!"
  }
];

const EXTRA_OFFICIAL_WORDS = [
  { w: "place", s: "Lugar", ph: "pleis", lev: 2 },
  { w: "play", s: "Jugar / Obra", ph: "plei", lev: 2 },
  { w: "poor", s: "Pobre / Humilde", ph: "pur", lev: 3 },
  { w: "quack", s: "Graznido de pato", ph: "kuak", lev: 4 },
  { w: "same", s: "Mismo / Igual", ph: "seim", lev: 3 },
  { w: "seal", s: "Foca / Sellar", ph: "sil", lev: 3 },
  { w: "seven", s: "Siete (7)", ph: "sé-ven", lev: 2 },
  { w: "ship", s: "Barco grande", ph: "ship", lev: 3 },
  { w: "short", s: "Corto / Bajo", ph: "short", lev: 2 },
  { w: "sing", s: "Cantar", ph: "sing", lev: 2 },
  { w: "slim", s: "Delgado", ph: "slim", lev: 3 },
  { w: "slow", s: "Lento", ph: "slou", lev: 2 },
  { w: "soft", s: "Suave", ph: "soft", lev: 2 },
  { w: "tall", s: "Alto", ph: "tol", lev: 2 },
  { w: "taxi", s: "Taxi", ph: "ták-si", lev: 3 },
  { w: "tent", s: "Carpa / Tienda de acampar", ph: "tent", lev: 3 },
  { w: "that", s: "Ese / Eso", ph: "dat", lev: 2 },
  { w: "thin", s: "Delgado / Fino", ph: "din", lev: 3 },
  { w: "this", s: "Este / Esto", ph: "dis", lev: 1 },
  { w: "those", s: "Esos / Esas", ph: "dous", lev: 3 },
  { w: "three", s: "Tres (3)", ph: "dri", lev: 2 },
  { w: "tiger", s: "Tigre", ph: "tái-ger", lev: 3 },
  { w: "trip", s: "Viaje / Paseo", ph: "trip", lev: 3 },
  { w: "truck", s: "Camión", ph: "trak", lev: 3 },
  { w: "under", s: "Debajo / Bajo", ph: "án-der", lev: 3 },
  { w: "up", s: "Arriba", ph: "ap", lev: 1 },
  { w: "vest", s: "Chaleco", ph: "vest", lev: 3 },
  { w: "visit", s: "Visitar", ph: "ví-sit", lev: 3 },
  { w: "week", s: "Semana", ph: "uik", lev: 3 },
  { w: "wife", s: "Esposa", ph: "uaif", lev: 4 },
  { w: "wing", s: "Ala (de ave)", ph: "uing", lev: 3 }
];

EXTRA_OFFICIAL_WORDS.forEach((item, index) => {
  const exists = WORDS_DATA.some(w => w.word.toLowerCase() === item.w.toLowerCase());
  if (!exists) {
    WORDS_DATA.push({
      id: `w_extra_${index}`,
      word: item.w,
      level: item.lev,
      phonetic: item.ph,
      spanish: item.s,
      synonyms: ["vocabulario de primer grado"],
      howToUseEs: `Usa '${item.w}' en tus oraciones diarias para practicar Spelling Bee.`,
      exampleEn: `We know the word ${item.w}.`,
      exampleEs: `Conocemos la palabra ${item.s.toLowerCase()}.`
    });
  }
});
